### ISSUE TITLE
Review Talent Initiative page before launch

### ISSUE THREAD

**Issue by lanebecker** [codeforamerica/content-team#19]
V1 of the Talent Initiative page is ready to go live and could use a content team review.

http://jekit.codeforamerica.org/codeforamerica/codeforamerica.org/talent-project/talent/

@davidrleonard and I are hoping to launch this ASAP, so a quick pass as soon as possible would be appreciated.

**Comment by ladyson** [comment]
This might be something to add for v2, but would love to see some photos/quotes from technologists in gov to give some color to what kinds of jobs and the people in them.

**Comment by lanebecker** [comment]
That's the plan! I'm actually doing a couple of interviews this month with technologists in gov andplan to feature them here. Suggests for interviewees? So far I've asked Amy Mok and Aaron Ogle, was going to ping Laura in Pittsburgh, too.

**Comment by dschrimmer** [comment]
Hey @lanebecker -- 

On both surveys: "Your information **with** NEVER be sold or transferred ...."  (change to will)

Love the rocketship. 

It's a little unclear what the relationship of this page is to the Fellowship. Especially because the survey asks if I'm interested in the Fellowship, a user might think that this is the official application or something. You might want to consider adding some more clarifying language.

**Comment by lanebecker** [comment]
@dschrimmer thanks. changes made. also removed a line of extraneous texts from the page as per suggestion from @Jaime-Alexis. @davidrleonard i think we're good to go. closing this issue for now.
